apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-shop
  labels:
    app: pet-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-shop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pet-shop
    spec:
      containers:
      - name: pet-shop
        image: harbor
        ports:
        - containerPort: 8080
          name: tomcat
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 256Mi
